function set_vars() {
	dont_cancel = true;
	meleeCharge = 16;
	melee_count = 0;
	last_shot = false;
	just_meleed = false;
	just_reset = true;
	cooldown_counter = 0;
	cooldownCounterMax = 20;
	just_countered = false;
	cooldown_taunt = 0;
	cooldownTauntMax = 10;
	cooldown_dash = 0;
	cooldownDashMax = 10;
	/*cooldown_hyper = 0;
	cooldownHyperMax = 0;*/
	cooldown_hyper_wait = 0;
	hyper_pressed = 0;
}