function set_vars() {
	dont_cancel = true;
	meleeCharge = 16;
	melee_count = 0;
	last_shot = false;
	just_meleed = false;
	just_reset = true;
	/*shockwaveCharge = 12;
	just_shockwaved = false;
	hookCharge = 6;
	just_hooked = false;*/
	cooldown_jump = 0;
	cooldownJumpMax = 5;
	cooldown_counter = 0;
	cooldownCounterMax = 20;
	just_countered = false;
	cooldown_dash = 0;
	cooldownDashMax = 10;
}